name = "RustLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RustLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0-rc4"

[[require]]
name = "Hax"
git = "https://github.com/cryspen/hax.git"
subDir = "hax-lib/proof-libs/lean"
rev = "lean-nightly"  # or a specific commit hash

[[lean_lib]]
name = "RustLean"
srcDir = "proofs/lean"
