-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [rust_lean_playground]
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace rust_lean_playground

/- [rust_lean_playground::add_with_carry]: loop 0:
   Source: 'src/lib.rs', lines 43:4-50:5 -/
def add_with_carry_loop
  (x : alloc.vec.Vec U32) (y : alloc.vec.Vec U32) (c0 : U8) (i : Usize) :
  Result (U8 × (alloc.vec.Vec U32))
  :=
  let i1 := alloc.vec.Vec.len x
  if i < i1
  then
    do
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceInst U32) x i
    let i3 ← (↑(UScalar.cast .U32 c0) : Result U32)
    let (sum, c1) ←
      (↑(core.num.U32.overflowing_add i2 i3) : Result (U32 × Bool))
    let i4 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSliceInst U32) y i
    let (sum1, c2) ←
      (↑(core.num.U32.overflowing_add sum i4) : Result (U32 × Bool))
    let i5 ← (↑(UScalar.cast_fromBool .U8 c1) : Result U8)
    let i6 ← (↑(UScalar.cast_fromBool .U8 c2) : Result U8)
    let c01 ← i5 + i6
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSliceInst U32) x
        i
    let i7 ← i + 1#usize
    let x1 := index_mut_back sum1
    add_with_carry_loop x1 y c01 i7
  else ok (c0, x)
partial_fixpoint

/- [rust_lean_playground::add_with_carry]:
   Source: 'src/lib.rs', lines 39:0-52:1 -/
@[reducible]
def add_with_carry
  (x : alloc.vec.Vec U32) (y : alloc.vec.Vec U32) :
  Result (U8 × (alloc.vec.Vec U32))
  :=
  add_with_carry_loop x y 0#u8 0#usize

end rust_lean_playground
